import os
import subprocess

import cv2
import pandas as pd

from extract_skeletons.config import B_EXPERIMENT_CONFIG, B_CHECKPOINT, BYTETRACK_DIR, frames_dir

def bytetrack(vid, n_segs):
    """
    Run ByteTrack on each trimmed video segment of a given video.

    For each segment, this function invokes the ByteTrack demo script on the
    corresponding trimmed video file and stores the tracking results using the
    default ByteTrack output structure.

    Parameters
    ----------
    vid : str
        Video filename or video identifier used to construct the segment paths.

    n_segs : int
        Number of trimmed video segments to process.

    Notes
    -----
    This function assumes that:
    - each trimmed segment is stored under ``frames_dir``,
    - ByteTrack is installed under ``BYTETRACK_DIR``,
    - the experiment configuration and checkpoint are provided through
      ``B_EXPERIMENT_CONFIG`` and ``B_CHECKPOINT``.

    The processed input path for segment ``j`` is assumed to be:

        frames_dir / f"{j+1}_trimmed_{vid}"

    Raises
    ------
    subprocess.CalledProcessError
        If the ByteTrack subprocess fails during execution.
    """
    for j in range(n_segs):
          command = [
              "python", "tools/demo_track.py", "video",  # Split "demo_track.py" and "video"
              "-f", B_EXPERIMENT_CONFIG,
              "-c", B_CHECKPOINT,
              "--path", os.path.join(frames_dir, f"{j+1}_trimmed_{vid}"),
              "--save_result",
              "--device", "gpu"
          ]

          subprocess.run(command, cwd=BYTETRACK_DIR, check=True)


def get_results_bytetrack():
    """
    Retrieve the names of the text files generated by ByteTrack.

    The function recursively scans the default ByteTrack visualization/results
    directory and collects all files with ``.txt`` extension.

    Returns
    -------
    list of str
        A list containing the names of all detected ``.txt`` result files.

    Notes
    -----
    The search is performed under:

        BYTETRACK_DIR / "YOLOX_outputs/yolox_x_mix_det/track_vis"

    Only filenames are returned, not absolute paths.
    """
    folder_path = os.path.join(
        BYTETRACK_DIR,
        "YOLOX_outputs/yolox_x_mix_det/track_vis",
    )

    txt_files = []

    for root, dirs, files in os.walk(folder_path):
        for file in files:
            if file.endswith(".txt"):
                txt_files.append(file)

    return txt_files


def select_best_per_frame(df, num_frames):
    """
    Select the highest-priority detection for each frame.

    Detections are ranked per frame using bounding-box area as the primary
    criterion and detection confidence as the secondary criterion. The best
    detection is retained for each frame. Frames without detections are kept in
    the output and filled with missing values.

    Parameters
    ----------
    df : pandas.DataFrame
        Input dataframe containing at least the following columns:
        ``frame``, ``w``, ``h``, and ``confidence``.

    num_frames : int
        Total number of frames to include in the output.

    Returns
    -------
    pandas.DataFrame
        A dataframe containing one row per frame in the range
        ``[1, num_frames]``. For frames with detections, the best-ranked
        detection is returned. For frames without detections, the corresponding
        row contains ``NaN`` values for detection-related fields.

    Notes
    -----
    The ranking rule is:
    1. larger bounding-box area first,
    2. higher confidence first.
    """
    df = df.copy()

    df["area"] = df["w"] * df["h"]
    df = df.sort_values(
        ["frame", "area", "confidence"],
        ascending=[True, False, False],
    )

    best = df.groupby("frame", as_index=False).first()

    full = pd.DataFrame({"frame": range(1, num_frames + 1)})
    best = full.merge(best, on="frame", how="left")

    return best
